```
Flores Aquino Luis Enrique
171564

```

In [1]:
import findspark
findspark.init()
 
import pyspark # only run after findspark.init()
from pyspark.sql import SparkSession
from pyspark import SparkContext
spark = SparkSession.builder.getOrCreate()
sc = SparkContext.getOrCreate()

In [3]:
#Creamos un RDD con 200 números aleatorios entre 1 y 80 000
import random
import numpy as np

# Creación de RDDs para trabajar

In [4]:
ValNumRDD = sc.parallelize(enumerate([random.randrange(1,80000) for x in range(200)]))
ValNumRDD.collect()

[(0, 78677),
 (1, 17834),
 (2, 13007),
 (3, 47871),
 (4, 42413),
 (5, 68261),
 (6, 47421),
 (7, 638),
 (8, 34272),
 (9, 33879),
 (10, 39680),
 (11, 69845),
 (12, 71359),
 (13, 50636),
 (14, 16716),
 (15, 46726),
 (16, 39741),
 (17, 15164),
 (18, 72280),
 (19, 34837),
 (20, 71705),
 (21, 37264),
 (22, 56951),
 (23, 5041),
 (24, 66082),
 (25, 69303),
 (26, 44360),
 (27, 22560),
 (28, 48141),
 (29, 20451),
 (30, 77173),
 (31, 8725),
 (32, 14357),
 (33, 63457),
 (34, 70130),
 (35, 8252),
 (36, 57325),
 (37, 74541),
 (38, 50151),
 (39, 4689),
 (40, 42203),
 (41, 27736),
 (42, 36767),
 (43, 6271),
 (44, 76876),
 (45, 54407),
 (46, 67798),
 (47, 21824),
 (48, 79015),
 (49, 59643),
 (50, 70244),
 (51, 1131),
 (52, 5022),
 (53, 42986),
 (54, 65174),
 (55, 47506),
 (56, 57646),
 (57, 32471),
 (58, 38849),
 (59, 36338),
 (60, 46173),
 (61, 64962),
 (62, 61742),
 (63, 18028),
 (64, 30444),
 (65, 68912),
 (66, 19594),
 (67, 38141),
 (68, 58875),
 (69, 66240),
 (70, 19033),
 (71, 1515),
 (72, 65259)

In [5]:
ValVectRDD = sc.parallelize(enumerate(np.random.random(size=(10,10))))
ValVectRDD.collect()

[(0,
  array([0.46997129, 0.87979162, 0.468592  , 0.51005056, 0.4145145 ,
         0.57310935, 0.51117053, 0.6925502 , 0.05352629, 0.73919656])),
 (1,
  array([0.79929682, 0.16302412, 0.65541745, 0.54228847, 0.56572423,
         0.59898879, 0.32005012, 0.19040829, 0.25258824, 0.6763764 ])),
 (2,
  array([0.17479978, 0.06850848, 0.63909742, 0.7935436 , 0.4792078 ,
         0.06925793, 0.45332418, 0.13018427, 0.59294353, 0.70168498])),
 (3,
  array([0.18648106, 0.69758402, 0.90239652, 0.12660522, 0.60421087,
         0.88883708, 0.78293124, 0.76342763, 0.68194455, 0.98020855])),
 (4,
  array([0.85882869, 0.47747034, 0.12143498, 0.57086278, 0.34949576,
         0.9529193 , 0.76995698, 0.266803  , 0.64933589, 0.38116381])),
 (5,
  array([0.01087064, 0.02347094, 0.94877726, 0.47936034, 0.53726644,
         0.24841554, 0.47691774, 0.36091268, 0.58006855, 0.54650858])),
 (6,
  array([0.1439867 , 0.45588409, 0.79287975, 0.38784958, 0.37174359,
         0.52320534, 0.35642352, 0.92468815, 0.118

In [22]:
ValVectBinRDD = sc.parallelize(enumerate(np.random.choice([0, 1], size=(10,10))))
ValVectBinRDD.collect()

[(0, array([1, 1, 0, 1, 1, 1, 1, 1, 0, 0])),
 (1, array([1, 0, 0, 0, 0, 0, 0, 1, 1, 1])),
 (2, array([1, 1, 0, 0, 1, 0, 1, 1, 1, 1])),
 (3, array([0, 1, 1, 1, 0, 0, 1, 1, 1, 1])),
 (4, array([1, 1, 1, 1, 1, 0, 0, 1, 0, 1])),
 (5, array([1, 1, 1, 1, 1, 1, 0, 0, 1, 0])),
 (6, array([0, 1, 1, 0, 1, 1, 1, 0, 1, 0])),
 (7, array([0, 1, 0, 0, 0, 0, 1, 0, 1, 0])),
 (8, array([1, 1, 1, 0, 0, 1, 0, 0, 1, 0])),
 (9, array([1, 0, 1, 0, 0, 1, 1, 1, 1, 1]))]

In [54]:
ValMatxRDD = sc.parallelize(enumerate(np.random.rand(10,3,3)))
ValMatxRDD.collect()

[(0,
  array([[5.71798282e-01, 4.44559824e-01, 7.46036343e-01],
         [7.92594732e-02, 5.98118753e-01, 5.49318978e-01],
         [7.71943256e-04, 8.00102487e-01, 5.22981155e-01]])),
 (1,
  array([[0.10911076, 0.53541683, 0.56874864],
         [0.21766427, 0.38358031, 0.59723593],
         [0.81848412, 0.36765953, 0.81144723]])),
 (2,
  array([[0.51872346, 0.55004093, 0.31972728],
         [0.47888028, 0.26982868, 0.6487898 ],
         [0.21957033, 0.92420798, 0.0231687 ]])),
 (3,
  array([[0.44630894, 0.11729806, 0.19052606],
         [0.46597256, 0.21278736, 0.28553493],
         [0.04521515, 0.4315522 , 0.46449775]])),
 (4,
  array([[0.8019095 , 0.62289346, 0.6382211 ],
         [0.45247016, 0.93251568, 0.94567832],
         [0.28286487, 0.85043685, 0.73070744]])),
 (5,
  array([[0.33059971, 0.03874118, 0.16493263],
         [0.38323402, 0.34227284, 0.23023345],
         [0.35805536, 0.76780555, 0.50706803]])),
 (6,
  array([[0.19721932, 0.93997185, 0.38228925],
         [0.917030

# SIMILITUD COSENO

In [6]:
def DistCos(Val1, Val2):
    return Val1*Val2/(Val1*Val1*Val2*Val2)
DistCos(15,54)

0.0012345679012345679

In [7]:
#Calculamos la distancia coseno de todas los valore
#Primero hacemos un producto cartesiano
cartNumRDD = ValNumRDD.cartesian(ValNumRDD)

#Agrupamos de la forma ((llave 1, llave 2),(valor 1, valor 2))
cartPointsParesRDD = cartNumRDD.map(lambda x: ((x[0][0], x[1][0]), (x[0][1],x[1][1])))

#Aplicamos la distancia de cosenos mediante una funcion lambda dentro de otra funcion
DistCosRDD = cartPointsParesRDD.map(lambda x: (x[0], DistCos(x[1][0],x[1][1])))

#Obtenemos la distancia coseno de cada producto cartesiano
statRDD = DistCosRDD.map(lambda x: x[1])

minv, maxv, meanv = statRDD.min(), statRDD.max(), statRDD.mean()
print (minv, maxv, meanv)

1.5760246714785397e-10 6.281367579349376e-06 7.2234138946818226e-09


# Distancia de Minkowski

In [8]:
def creatorMinkowski(p):
    def Minkowski(Val1, Val2):
        Temp = (abs(Val1-Val2)**p)
        return Temp.sum()**(1/p)
    return Minkowski

In [9]:
Minkowski = creatorMinkowski(2)

In [10]:
#Calculamos la distancia Minkowski de todas los valores
#Primero hacemos un producto cartesiano
cartVectRDD = ValVectRDD.cartesian(ValVectRDD)

#Agrupamos de la forma ((llave 1, llave 2),(valor 1, valor 2))
cartPointsParesRDD = cartVectRDD.map(lambda x: ((x[0][0], x[1][0]), (x[0][1],x[1][1])))

#Aplicamos la distancia de cosenos mediante una funcion lambda dentro de otra funcion
DistMinkRDD = cartPointsParesRDD.map(lambda x: (x[0], Minkowski(x[1][0],x[1][1])))

#Obtenemos la distancia coseno de cada producto cartesiano
statRDD = DistMinkRDD.map(lambda x: x[1])

minv, maxv, meanv = statRDD.min(), statRDD.max(), statRDD.mean()
print (minv, maxv, meanv)

0.0 1.5735441521482092 1.0163720543654766


# Distancia de Jaccard

In [97]:
def Jaccard(val1,val2):
    old_settings = np.seterr(divide='raise')
    try:
        temp = sum(val1*val2)/sum(np.logical_xor(val1,val2))
    except FloatingPointError:
        temp = 1
    return 1 - temp
val1 = np.array([1,0,1,0,0])
val2 = np.array([0,1,1,0,0])
Jaccard(val1,val2)

0.5

In [99]:
#Calculamos la distancia Minkowski de todas los valores
#Primero hacemos un producto cartesiano
cartVectBinRDD = ValVectBinRDD.cartesian(ValVectBinRDD)

#Agrupamos de la forma ((llave 1, llave 2),(valor 1, valor 2))
cartPointsParesRDD = cartVectBinRDD.map(lambda x: ((x[0][0], x[1][0]), (x[0][1],x[1][1])))

#Aplicamos la distancia de cosenos mediante una funcion lambda dentro de otra funcion
DistJaccRDD = cartPointsParesRDD.map(lambda x: (x[0], Jaccard(x[1][0],x[1][1])))

#Obtenemos la distancia coseno de cada producto cartesiano
statRDD = DistJaccRDD.map(lambda x: x[1])
minv, maxv, meanv = statRDD.min(), statRDD.max(), statRDD.mean()
print (minv, maxv, meanv)

-1.5 0.875 0.16666666666666666


# Estandarización

In [55]:
def Estandarizacion(Val1):
    valTemp = []
    for k in range (Val1.shape[0]):
        valTemp.append((Val1[k]+np.mean(Val1[k]))/np.std(Val1[k]))
    return np.asmatrix(valTemp)
Val1 = np.random.rand(3,4)
print(Val1)
Estandarizacion(Val1)

[[0.05123063 0.84596248 0.07354012 0.95397091]
 [0.60263523 0.30862434 0.93081903 0.52939766]
 [0.62317936 0.65003997 0.34310584 0.6389091 ]]


matrix([[1.26582051, 3.15533082, 1.3188623 , 3.41212565],
        [5.35813455, 4.04040619, 6.8290226 , 5.02989086],
        [9.28933635, 9.49954674, 7.09748829, 9.41243688]])

In [71]:
#Aplicamos la estandarización mediante una funcion lambda dentro de otra funcion
StdRDD = ValMatxRDD.map(lambda x: (x[0], Estandarizacion(x[1])))

#Obtenemos la estandarización de cada elemento
statRDD = StdRDD.map(lambda x: x[1])
statRDD.collect()


[matrix([[ 9.38106264,  8.35141548, 10.79104296],
         [ 2.08668055,  4.30459435,  4.09599503],
         [ 1.33391188,  3.74589987,  2.90968345]]),
 matrix([[2.45403583, 4.49122503, 4.6505078 ],
         [3.97224536, 5.0401396 , 6.4153026 ],
         [7.03876963, 4.90096168, 7.00540071]]),
 matrix([[9.62366238, 9.93071508, 7.67260112],
         [6.09551097, 4.74666102, 7.191807  ],
         [1.5730486 , 3.39446739, 1.06536976]]),
 matrix([[4.94666179, 2.61394463, 3.13313786],
         [7.39809019, 5.01927764, 5.70278063],
         [1.88572281, 3.91520774, 4.08827551]]),
 matrix([[18.385792  , 16.17621451, 16.3654021 ],
         [ 5.35759058,  7.44964751,  7.5070108 ],
         [ 3.70155871,  6.02504697,  5.5349067 ]]),
 matrix([[ 4.25634704,  1.81429188,  2.87016812],
         [10.85224551, 10.21885737,  8.48637731],
         [ 5.32872019,  7.74841079,  6.20868209]]),
 matrix([[2.22912541, 4.58191557, 2.81536468],
         [4.1711775 , 2.06641317, 2.03367999],
         [2.77085477,

# Escalonamiento

In [48]:
def Escalonamiento(Val1):
    valTemp = []
    for k in range (Val1.shape[0]):
        maxVal = np.max(Val1[k])
        valTemp.append((Val1[k]-maxVal)/ (maxVal-np.min(Val1[k])))
    return np.asmatrix(valTemp)
Val1 = np.random.rand(3,4)
print(Val1)
print("===")
Estandarizacion(Val1)

[[0.97905161 0.28280459 0.0996767  0.80566282]
 [0.37136098 0.01933104 0.41816672 0.2386946 ]
 [0.66728589 0.17514312 0.72847569 0.74976467]]
===


matrix([[4.2045017 , 2.2796763 , 1.77340596, 3.72515581],
        [4.09231601, 1.81735462, 4.39479383, 3.23497159],
        [5.29046482, 3.20328116, 5.54997152, 5.64025834]])

In [69]:
#Aplicamos la funcion de escalonamiento mediante una funcion lambda dentro de otra funcion
EscalonamientoRDD = ValMatxRDD.map(lambda x: (x[0], Escalonamiento(x[1])))
#Obtenemos la matriz escalonada de cada elemento
statRDD = EscalonamientoRDD.map(lambda x: x[1])
statRDD.collect()

[matrix([[-0.57794902, -1.        ,  0.        ],
         [-1.        ,  0.        , -0.09405204],
         [-1.        ,  0.        , -0.34669178]]),
 matrix([[-1.        , -0.07251755,  0.        ],
         [-1.        , -0.56288612,  0.        ],
         [ 0.        , -1.        , -0.01560894]]),
 matrix([[-0.13597751,  0.        , -1.        ],
         [-0.44835607, -1.        ,  0.        ],
         [-0.78202767,  0.        , -1.        ]]),
 matrix([[ 0.        , -1.        , -0.77742984],
         [ 0.        , -1.        , -0.71267051],
         [-1.        , -0.07857599,  0.        ]]),
 matrix([[ 0.        , -1.        , -0.91437839],
         [-1.        , -0.0266878 ,  0.        ],
         [-1.        ,  0.        , -0.21095018]]),
 matrix([[ 0.        , -1.        , -0.56762801],
         [ 0.        , -0.26771912, -1.        ],
         [-1.        ,  0.        , -0.63633288]]),
 matrix([[-1.        ,  0.        , -0.75083232],
         [ 0.        , -0.98468621, -1